title: Sumathi M
logo: https://github.com/sumathi154.png # This automatically pulls your GitHub profile picture
description: >
  AI Developer & PhD Researcher [cite: 17, 71]
  <br>
  Specialist in RAG and Data Analytics [cite: 11, 17]
  <br><br>
  <a href="mailto:sumahalesh4@gmail.com">Email</a> [cite: 2]
  <br>
  <a href="https://github.com/sumathi154">GitHub</a>
theme: jekyll-theme-minimal
